# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable: false
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: auto
    option: [ auto, ]
  ScreenshotMethod:
    value: auto
    option: [ auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy ]
  ControlMethod:
    value: MaaTouch
    option: [ minitouch, MaaTouch ]
  AdbRestart: false
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
Error:
  Restart:
    value: game
    option: [ game, game_emulator ]
  SaveError: true
  ScreenshotLength: 1
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Optimization:
  ScreenshotInterval: 0.3
  CombatScreenshotInterval: 1.0
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game ]

# ==================== Daily ====================

Dungeon:
  Name:
    # Options will be injected in config updater
    value: Calyx_Golden_Treasures
    option: [Calyx_Golden_Treasures, ]
  NameAtDoubleCalyx:
    # Options will be injected in config updater
    value: Calyx_Golden_Treasures
    option: [ do_not_participate, ]
  Team:
    value: 1
    option: [ 1, 2, 3, 4, 5, 6 ]

Assignment:
  Duration:
    value: 20
    option: [4, 8, 12, 20]
  # Options in Name_x will be injected in config updater
  Name_1:
    value: Nameless_Land_Nameless_People
    option: [Nameless_Land_Nameless_People, ] 
  Name_2:
    value: Akashic_Records
    option: [Nameless_Land_Nameless_People, ] 
  Name_3:
    value: The_Invisible_Hand
    option: [Nameless_Land_Nameless_People, ] 
  Name_4:
    value: Nine_Billion_Names
    option: [Nameless_Land_Nameless_People, ] 