# --------------------
# Define default values
# --------------------

# ==================== Alas ====================


# ==================== Daily ====================

Dungeon:
  Scheduler:
    Enable: true
Weekly:
  Scheduler:
    Enable: true
DailyQuest:
  Scheduler:
    Enable: true
BattlePass:
  Scheduler:
    Enable: true
Assignment:
  Scheduler:
    Enable: true
Freebies:
  Scheduler:
    Enable: true
