# Translations web gui
# This will insert to `config/i18n/{lang}.json`, under key `Gui`

Aside:
  Install:
  Develop:
  Performance:
  Setting:
  AddAlas:

Button:
  Start:
  Stop:
  ScrollON:
  ScrollOFF:
  ClearLog:
  Setting:
  CheckUpdate:
  ClickToUpdate:
  RetryUpdate:
  CancelUpdate:

Toast:
  DisableTranslateMode:
  ConfigSaved:
  AlasIsRunning:
  ClickToUpdate:

Status:
  Running:
  Inactive:
  Warning:
  Updating:

MenuAlas:
  Overview:
  Log:

MenuDevelop:
  HomePage:
  Translate:
  Update:
  Remote:
  Utils:

Overview:
  Scheduler:
  Log:
  Running:
  Pending:
  Waiting:
  NoTask:

AddAlas:
  PopupTitle:
  NewName:
  CopyFrom:
  Confirm:
  FileExist:

Update:
  UpToDate:
  HaveUpdate:
  UpdateStart:
  UpdateWait:
  UpdateRun:
  UpdateSuccess:
  UpdateFailed:
  UpdateChecking:
  UpdateCancel:
  UpdateFinish:
  Local:
  Upstream:
  Author:
  Time:
  Message:
  DisabledWarn:
  DetailedHistory:

Remote:
  Running:
  NotRunning:
  NotEnable:
  EntryPoint:
  ConfigureHint:
  SSHNotInstall:

Text:
  InvalidFeedBack: