# Translations web gui
# This will insert to `config/i18n/{lang}.json`, under key `Gui`

Aside:
  Install:
  Home:
  Develop:
  Performance:
  Setting:
  AddAlas:

Button:
  Start:
  Stop:
  ScrollON:
  ScrollOFF:
  DashboardON:
  DashboardOFF:
  ClearLog:
  Setting:
  CheckUpdate:
  ClickToUpdate:
  RetryUpdate:
  CancelUpdate:

Toast:
  DisableTranslateMode:
  ConfigSaved:
  AlasIsRunning:
  ClickToUpdate:

Status:
  Running:
  Inactive:
  Warning:
  Updating:

MenuAlas:
  Overview:
  Log:

MenuDevelop:
  HomePage:
  Translate:
  Update:
  Remote:
  Utils:

Overview:
  Scheduler:
  Dashboard:
  Log:
  Running:
  Pending:
  Waiting:
  NoTask:

Dashboard:
  TimeError:
  JustNow:
  MinutesAgo:
  HoursAgo:
  DaysAgo:
  MonthsAgo:
  LongTimeAgo:
  NoData:
  Oil:
  Coin:
  Gem:
  Cube:
  Pt:
  YellowCoin:
  PurpleCoin:
  ActionPoint:
  Merit:
  Medal:
  Core:
  GuildCoin:

AddAlas:
  PopupTitle:
  NewName:
  CopyFrom:
  Confirm:
  FileExist:
  InvalidChar:
  InvalidPrefixTemplate:
  Manage:

AppManage:
  PageTitle:
  TitleNew:
  NewName:
  CopyFrom:
  NameExist:
  InvalidChar:
  InvalidPrefixTemplate:
  Back:
  New:
  Import:
  Export:
  Delete:
  OverrideWarning:
  ImportSuccess:
  NewSuccess:
  Name:
  Mod:
  Actions:

Update:
  UpToDate:
  HaveUpdate:
  UpdateStart:
  UpdateWait:
  UpdateRun:
  UpdateSuccess:
  UpdateFailed:
  UpdateChecking:
  UpdateCancel:
  UpdateFinish:
  Local:
  Upstream:
  Author:
  Time:
  Message:
  DisabledWarn:
  DetailedHistory:

Remote:
  Running:
  NotRunning:
  NotEnable:
  EntryPoint:
  ConfigureHint:
  SSHNotInstall:

Text:
  InvalidFeedBack:
  Clear:
  EnterPassword:
  ChooseFile: