# --------------------
# Define non-modifiable values
# --------------------

# ==================== Alas ====================

Restart:
  Scheduler:
    Enable:
      value: true
      display: disabled
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 00:00

# ==================== Farm ====================

Main:
  Campaign:
    Event: campaign_main
Main2:
  Campaign:
    Event: campaign_main
Main3:
  Campaign:
    Event: campaign_main
GemsFarming:
  Campaign:
    Event:
      value: campaign_main
    Mode: normal
    AmbushEvade: true
  StopCondition:
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false

# ==================== Event ====================

Event:
  Campaign:
    Mode: normal
    Event:
      display: disabled
    AmbushEvade: true
Event2:
  Campaign:
    Mode: normal
    Event:
      display: disabled
    AmbushEvade: true
EventA:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
EventB:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
EventC:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
EventD:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
EventSp:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: sp
    Event:
      display: disabled
    Mode: normal
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
  Submarine:
    AutoSearchMode: sub_standby
Raid:
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: false
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
  Emotion:
    Fleet2Value: 119
    Fleet2Record: 2020-01-01 00:00:00
    Fleet2Control: prevent_yellow_face
    Fleet2Recover: not_in_dormitory
    Fleet2Oath: false
RaidDaily:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event:
      display: disabled
    Mode: normal
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: false
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
  Emotion:
    Fleet2Value: 119
    Fleet2Record: 2020-01-01 00:00:00
    Fleet2Control: prevent_yellow_face
    Fleet2Recover: not_in_dormitory
    Fleet2Oath: false
MaritimeEscort:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00

# ==================== Reward ====================

Commission:
  Scheduler:
    Enable:
      value: true
      type: lock
    SuccessInterval: 30-60
    FailureInterval: 30-60
    ServerUpdate: 00:00
Tactical:
  Scheduler:
    SuccessInterval: 30-60
    FailureInterval: 120-240
    ServerUpdate: 00:00
Research:
  Scheduler:
    Enable:
      value: true
      type: lock
    SuccessInterval: 30-60
    FailureInterval: 30-60
    ServerUpdate: 00:00
Dorm:
  Scheduler:
    SuccessInterval: 278
    FailureInterval: 278
    ServerUpdate: 00:00
Meowfficer:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
Guild:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00, 06:00, 12:00, 18:00, 21:00
Reward:
  Scheduler:
    Enable:
      value: true
      type: lock
    SuccessInterval: 120-240
    FailureInterval: 120-240
    ServerUpdate: 00:00
ShopFrequent:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00, 12:00, 18:00
ShopOnce:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
Shipyard:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 04:00
Gacha:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
Freebies:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00

# ==================== Daily ====================

Daily:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
Hard:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
Exercise:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00, 12:00, 18:00
Sos:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Name: dynamic
    Event: campaign_main
    Mode: normal
    UseClearMode: true
    UseFleetLock: true
    UseAutoSearch: false
    Use2xBook: false
    AmbushEvade: true
  StopCondition:
    RunCount: 0
    MapAchievement: non_stop
    StageIncrease: false
    GetNewShip: false
    ReachLevel: 0
  Submarine:
    AutoSearchMode: sub_standby
WarArchives:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
  Campaign:
    Mode: normal
    AmbushEvade: true

# ==================== Opsi ====================

OpsiAshAssist:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiAshBeacon:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiExplore:
  Scheduler:
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 00:00
OpsiShop:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiVoucher:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiDaily:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiObscure:
  Scheduler:
    SuccessInterval: 60
    FailureInterval: 60
    ServerUpdate: 00:00
OpsiAbyssal:
  Scheduler:
    SuccessInterval: 60
    FailureInterval: 60
    ServerUpdate: 00:00, 12:00
OpsiArchive:
  Scheduler:
    SuccessInterval: 60
    FailureInterval: 60
    ServerUpdate: 00:00
OpsiStronghold:
  Scheduler:
    SuccessInterval: 60
    FailureInterval: 60
    ServerUpdate: 00:00
OpsiMeowfficerFarming:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 30
    ServerUpdate: 00:00
OpsiHazard1Leveling:
  Scheduler:
    SuccessInterval: 30
    FailureInterval: 60
    ServerUpdate: 00:00
  OpsiFleet:
    Submarine: false
