# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Dungeon:
      - Scheduler
      - Dungeon
      - DungeonDaily
      - DungeonSupport
      - DungeonStorage
    DailyQuest:
      - Scheduler
      - AchievableQuest
      - DailyStorage
    BattlePass:
      - Scheduler
    Assignment:
      - Scheduler
      - Assignment

# ==================== Rogue ====================

Rogue:
  menu: 'list'
  page: 'setting'
  tasks:
    Rogue:
      - Scheduler
      - Rogue
