# --------------------
# Define default values
# --------------------

# ==================== Maa ====================
MaaStartup:
  Scheduler:
    Enable: true

MaaMaterial:
  Scheduler:
    FailureInterval: 240

MaaFight:
  Scheduler:
    SuccessInterval: 240
