# --------------------
# Define non-modifiable values
# --------------------

# ==================== Maa ====================

MaaStartup:
  Scheduler:
    Enable:
      value: true
      display: disabled
    SuccessInterval: 0
    FailureInterval: 0
    ServerUpdate: 04:00

MaaMaterial:
  Scheduler:
    FailureInterval: 480

MaaAnnihilation:
  Scheduler:
    SuccessInterval: 480
  MaaFight:
    Stage: Annihilation
    Medicine: 0
    Stone: 0
    Times: 5
    Drops: null
    DrGrandet: false

MaaFight:
  Scheduler:
    SuccessInterval: 480
  MaaFight:
    Medicine: 0
    Stone: 0
    Times: 0
    Drops: null
    DrGrandet: false

MaaRecruit:
  Scheduler:
    SuccessInterval: 180

MaaAward:
  Scheduler:
    ServerUpdate: 04:00, 16:00
