# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Maa ====================

Maa:
  - MaaEmulator
  - MaaRecord
  - Emulator
  - Error
  - Optimization

MaaStartup:
  - Scheduler

MaaRestart:
  - Scheduler
  - MaaRestart

MaaAnnihilation:
  - Scheduler
  - MaaFight

MaaMaterial:
  - Scheduler
  - MaaFight

MaaFight:
  - Scheduler
  - MaaFight
  - MaaFightWeekly

MaaRecruit:
  - Scheduler
  - MaaRecruit

MaaInfrast:
  - Scheduler
  - MaaInfrast
  - MaaCustomInfrast

MaaMall:
  - Scheduler
  - MaaMall

MaaAward:
  - Scheduler

MaaRoguelike:
  - Scheduler
  - MaaRoguelike

MaaReclamationAlgorithm:
  - Scheduler

# ==================== Tool ====================

MaaCopilot:
  - MaaCopilot