on:
  workflow_dispatch:
  push:
  schedule:
    # UTC 21:00 -> CST (China) 5:00
    - cron: '0 21 * * *'

name: Gitee mirror

jobs:
  run:
    name: Gitee mirror
    runs-on: ubuntu-latest
    steps:
      - name: Get repo and time
        id: info
        uses: actions/github-script@v3.1
        with:
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
            return context.repo.repo;

      - name: Cache src repos
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-list-

      - name: Mirror the Github repos to Gitee.
        # https://github.com/Yikun/hub-mirror-action
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/MengNianxiaoyao
          dst: gitee/MengNianxiaoyao
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'AzurLaneAutoScript'
          cache_path: /github/workspace/hub-mirror-cache
          account_type: user
          force_update: true
          timeout: '30m'

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
